highlighter: rouge
markdown: kramdown
columnist:
  paths:
  - _posts
permalink: /:lang/:categories/:title/
prose:
  rooturl: '_posts'
  media: 'assets/blog/media'
  metadata:
    _posts:
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: "false"
      - name: "layout"
        field:
          element: "hidden"
          label: "layout"
          value: "blog"
      - name: "title"
        field:
          label: "title"
          element: "text"
          value: "An Awesome Title"
      - name: "permalink"
        field:
          element: "text"
          label: "permalink"
          value: "/en/blog/title-of-post"
      - name: "lang"
        field:
          element: "hidden"
          label: "lang"
          value: "en"
      - name: "category"
        field:
          element: "hidden"
          label: "category"
          value: "blog"
      - name: "author"
        field:
          element: "select"
          label: "author"
          placeholder: "Choose author"
          value: personal
          options:
            - name: "Paul Stephens"
              value: Paul Stephens
            - name: "Jeff Haack"
              value: Jeff Haack
            - name: "Marta Mills"
              value: Marta Mills
            - name: "Tako Kobakhidze"
              value: Tako Kobakhidze
            - name: "Tom Allen"
              value: Tom Allen
            - name: "Alessandro Mambelli"
              value: Alessandro Mambelli
      - name: "thumb-big"
        field:
          element: "text"
          label: "thumb-photo (Ideally 480x125)"
          value: "/assets/blog/media/default-thumb.jpg"
      - name: "thumb-fb"
        field:
          element: "text"
          label: "Social Media photo (Ideally landscape, more wide than high)"
          value: "/assets/blog/media/default-fb.jpg"
t:
  en:
    navbar: 
      home:  "Home"
      about: "About the TCT"
      goals: "Goals"
      faq: "FAQ"
      get-involved: "Get Involved"
      gear: "Gear"
      blog: "Blog"
    newsletter:
      subscribe: "Subscribe to our newsletter"
      required: "indicates required"
      email: "Email Address"
      first-name: "First Name"
      last-name: "Last Name"
      country: "Country"
      button: "Subscribe"
    footer:
      the-tcteam: "The TCTeam"
      paul: "Paul Stephens"
      paul-job: "Executive Director"
      jeff: "Jeff Haack"
      jeff-job: "Cartographer"
      laura: "Laura Santos-Bishop"
      laura-job: "Trail Development"
      james: "James Scipioni"
      james-job: "Trail Development"
      marta: "Marta Mills"
      marta-job: "Stakeholder Engagement, Communications"
      vahagn: "Vahagn Vardumyan"
      vahagn-job: "Trail Development"
      tom: "Tom Allen"
      tom-job: "Trail Exploration"
      alessandro: "Alessandro Mambelli"
      alessandro-job: "Trail Exploration"
      copyright: "Copyright &copy; 2016 Transcaucasian Trail Association. All rights reserved."
  ka:
    navbar: 
      home:  "მთავარი"
      about: "About the TCT"
      goals: "მიზნები"
      faq: "კითხვა-პასუხი"
      get-involved: "შემოგვიერთდი"
      gear: "Gear"
      blog: "Blog"
    newsletter:
      subscribe: "Subscribe to our newsletter"
      required: "indicates required"
      email: "Email Address"
      first-name: "First Name"
      last-name: "Last Name"
      country: "Country"
      button: "Subscribe"
    footer:
      the-tcteam: "The TCTeam"
      paul: "Paul Stephens"
      paul-job: "Executive Director"
      jeff: "Jeff Haack"
      jeff-job: "Cartographer"
      laura: "Laura Santos-Bishop"
      laura-job: "Trail Development"
      james: "James Scipioni"
      james-job: "Trail Development"
      marta: "Marta Mills"
      marta-job: "Stakeholder Engagement, Communications"
      vahagn: "Vahagn Vardumyan"
      vahagn-job: "Trail Development"
      tom: "Tom Allen"
      tom-job: "Trail Exploration"
      alessandro: "Alessandro Mambelli"
      alessandro-job: "Trail Exploration"
      copyright: "Copyright &copy; 2016 Transcaucasian Trail Association. All rights reserved."
  hy:
    navbar: 
      home:  "Home"
      about: "About the TCT"
      goals: "Goals"
      faq: "FAQ"
      get-involved: "Get Involved"
      gear: "Gear"
      blog: "Blog"
    newsletter:
      subscribe: "Գրանցվեք մեր ամսագրին"
      required: "Պարտադիր տվյալներ"
      email: "Էլ. փոստի հասցե"
      first-name: "Անուն"
      last-name: "Ազգանուն"
      country: "Երկիր"
      button: "Անդամագրվել"
    footer:
      the-tcteam: "ԱԿԱ-ի թիմը"
      paul: "Փոլ Սթեֆընս"
      paul-job: "Գործադիր Տնօրեն"
      jeff: "Ջեֆ Հաաք"
      jeff-job: "Քարտեզագիր"
      laura: "Լաուրա Սանտոս-Բիշոփ"
      laura-job: "Արահետների Զարգացում"
      james: "Ջեյմս Սցիպիոնի"
      james-job: "Արահետների Զարգացում"
      marta: "Մարտա Միլզ"
      marta-job: "Շահառուների Ներգրավվածություն"
      vahagn: "Վահագն Վարդումյան"
      vahagn-job: "Արահետների Զարգացում"
      tom: "Թոմ Ալլեն"
      tom-job: "Արահետների Հայտնաբերում"
      alessandro: "Ալեսանդրո Մամբրելի"
      alessandro-job: "Արահետների Հայտնաբերում"
      copyright: "Հեղինակային իրավունք © 2016 Անդրկովկասյան Արահետ Ասոցիացիա: Բոլոր իրավունքները պաշտպանված են:"
  ru:
    navbar: 
      home:  "Home"
      about: "About the TCT"
      goals: "Goals"
      faq: "FAQ"
      get-involved: "Get Involved"
      gear: "Gear"
      blog: "Blog"
    newsletter:
      subscribe: "Subscribe to our newsletter"
      required: "indicates required"
      email: "Email Address"
      first-name: "First Name"
      last-name: "Last Name"
      country: "Country"
      button: "Subscribe"
    footer:
      the-tcteam: "The TCTeam"
      paul: "Paul Stephens"
      paul-job: "Executive Director"
      jeff: "Jeff Haack"
      jeff-job: "Cartographer"
      laura: "Laura Santos-Bishop"
      laura-job: "Trail Development"
      james: "James Scipioni"
      james-job: "Trail Development"
      marta: "Marta Mills"
      marta-job: "Stakeholder Engagement, Communications"
      vahagn: "Vahagn Vardumyan"
      vahagn-job: "Trail Development"
      tom: "Tom Allen"
      tom-job: "Trail Exploration"
      alessandro: "Alessandro Mambelli"
      alessandro-job: "Trail Exploration"
      copyright: "Copyright &copy; 2016 Transcaucasian Trail Association. All rights reserved."
#baseurl: 'http://transcaucasiantrail.org/'
#baseurl: 'http://localhost:4000/'
